      - name: Create config file
        env:
          GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          SCALE_APP_EMAIL: ${{ secrets.SCALE_APP_EMAIL }}
          SCALE_APP_PASSWORD: ${{ secrets.SCALE_APP_PASSWORD }}
        run: |
          cat << 'EOF' > config.yml
          fitdays_to_garmin:
            from: SCALE_EMAIL_PLACEHOLDER:SCALE_PASSWORD_PLACEHOLDER
            to: GARMIN_USERNAME_PLACEHOLDER:GARMIN_PASSWORD_PLACEHOLDER
          EOF
          sed -i "s|SCALE_EMAIL_PLACEHOLDER|${SCALE_APP_EMAIL}|g" config.yml
          sed -i "s|SCALE_PASSWORD_PLACEHOLDER|${SCALE_APP_PASSWORD}|g" config.yml
          sed -i "s|GARMIN_USERNAME_PLACEHOLDER|${GARMIN_USERNAME}|g" config.yml
          sed -i "s|GARMIN_PASSWORD_PLACEHOLDER|${GARMIN_PASSWORD}|g" config.yml

      - name: Run SmartScaleConnect Sync
        run: go run main.go -c config.yml
