name: Smart Scale Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1-5'
    - cron: '0 8 * * 0,6'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Create config file
        env:
          GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          SCALE_APP_EMAIL: ${{ secrets.SCALE_APP_EMAIL }}
          SCALE_APP_PASSWORD: ${{ secrets.SCALE_APP_PASSWORD }}
        run: |
          cat <<EOF > config.json
          {
            "fitdays": {
              "email": "$SCALE_APP_EMAIL",
              "password": "$SCALE_APP_PASSWORD",
              "destinations": ["garmin"]
            },
            "aphealth": {
              "email": "$SCALE_APP_EMAIL",
              "password": "$SCALE_APP_PASSWORD",
              "destinations": ["garmin"]
            },
            "garmin": {
              "email": "$GARMIN_USERNAME",
              "password": "$GARMIN_PASSWORD"
            }
          }
          EOF

      - name: Run SmartScaleConnect Sync
        run: go run main.go -v -c config.json
